# Use an empty string if you have multiple domain linking to your website
# This string is used to generate the absolute URL for your assets.
#baseURL = 'https://waxpraxis.org/'
defaultContentLanguage = 'en'
# Emoji in markdown files
enableEmoji = true
languageCode = 'en-us'
# Number of blog post per page
paginate = 10
theme = 'pico'
# Title of the website is used for the meta tag title
# and the square icon (not the favicon)
title = 'waxpraxis'


[params]
subtitle = 'The art & technology of Branden Hall'
customCSS = [
	"style/style.css",
	"style/theme.sass",
] # Path relative to assets folder
customJS = ["js/console.js"] # Path relative to assets folder
# Homepage description
# For blog page description you can overwrite it 
# in the front matter
description = "Personal website of Branden 'Wax' Hall"
email = "bhall@waxpraxis.org"
favicon = '/favicon.ico'
# Dark mode support
# Supported value are :
# - off
# - always
# If commented the theme will use the browser theme.
# darkMode = 'always'

# Social parameters for contact_icons widget
[[params.social]]
alt = "email icon"
icon = "/icons/email.svg"
name = "email"
url = "mailto:bhall@waxpraxis.org"

[[params.social]]
alt = "github icon"
blank = true
icon = "/icons/github.svg"
name = "github"
url = "https://github.com/"

# Navigation bar
[menu]

[[menu.main]]
identifier = "home" # identifier is use for translations
url = "/" 
weight = 10 

[[menu.main]]
identifier = "articles" # identifier is use for translations
url = "/articles/" 
weight = 20

[[menu.main]]
identifier = "portfolio" # identifier is use for translations
url = "/portfolio/" 
weight = 20 

# Syntax highlighting
[markup.highlight]
guessSyntax = true 
lineNumbersInTable = true 
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2 

[taxonomies]
category = "categories"
tag = "tags"

